<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DNHper\**" />
    <EmbeddedResource Remove="DNHper\**" />
    <None Remove="DNHper\**" />
    <Page Remove="DNHper\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EmbedIO" Version="3.5.2" />
    <PackageReference Include="HttpMultipartParser" Version="8.4.0" />
    <PackageReference Include="ini-parser-netstandard" Version="2.5.2" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="ReactiveUI.WPF" Version="20.1.1" />
    <PackageReference Include="YKT.AI.TotalApi" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudDisk\CloudDisk.csproj" />
    <ProjectReference Include="..\DNHper\DNHper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
